### ISSUE TITLE
Android doze and Newtifry

### ISSUE THREAD

**Issue by Browbeaten** [thunderace/newtifry#10]
I intend to use Newtifry for various private messages. I understand that messages may be delayed in the system.  However I suspect that Newtifry messages are received by my mobile, but are sometimes not announced until I move the phone.  My understanding is that this is a feature of Android 6.0.1 Marshmallow's 'doze' state.  The GCM documentation for Marshmallow indicates that messages can have a 'high' or 'normal' priority, but Newtifry has priorities 0 - 3.  Messages with a 'high' priority should wake Marshmallow from doze.  How can I send a GCM message via Newtifry with a 'high' priority?

**Comment by Browbeaten** [comment]
Thanks, I look forward to it!

Thanks for the quick response too!

Best wishes

Mike

**Comment by thunderace** [comment]
Done. You can test (i have no android M).

**Comment by Browbeaten** [comment]
Hi,

I've done a quick test and it still works.

But really I need to get the phone to doze, and then see if it still works.

I send myself a message via newtifry every morning, and the phone is normally dozing then (and so am 
I).  So tomorrow morning I'll have a good idea if it's worked. And I'll let you know.

Thanks again.

Mike

**Comment by Browbeaten** [comment]
Hi. Well, it seems to work. I get notifications within 5 minutes when the phone is dozing. This 
compares with 30 to 40 minutes or longer before you changed it.  So thanks again.

Mike

**Comment by thunderace** [comment]
Good.
