### ISSUE TITLE
2 notifications pour un seul évènement

### ISSUE THREAD

**Issue by RCani** [thunderace/newtifry#2]
Je reçois 2 messages de notification identiques lorsqu'un seul événement se produit.
Je constate également que pour mon profil il y a création automatique de périphériques identiques sans que je fasse quelque chose.
Auriez-vous une explication à cela ? Y a t-il une solution pour éviter ces doublons ?

**Comment by aandroide** [comment]
salut ,
vous pouvez avoir une esquisse pour Arduino newtifry pas pro mais la version classique?

**Comment by thunderace** [comment]
Hello,
See here : http://kd8bxp.blogspot.fr/2015/04/20150221-ping-sensor-iot-trigger-using.html
