### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by pengos** [thunderace/newtifry#3]
the first notification tone ring but the second one no! why?
thank you...

**Comment by thunderace** [comment]
I think it's the same with vibration no?

**Comment by pengos** [comment]
for example... if i receive 3 notifications only the first one ring. Second and third are only displayed.
If I read them every time all sound

**Comment by thunderace** [comment]
OK, it's an Android behavior. As there is only one notification for X messages, Android ring or vibrate only for the first message. It's not Newtifry related.
You have the same thing with gmail notification for example.

**Comment by aandroide** [comment]
Hi, I am trying to use your php script and not to pushingbox.
I can not understand how to fill in the script where it says:

newtifry.php
$ Options = getopt ("s: t: m: u: p: d:");

function usage ()
{
echo "Usage:", $ _SERVER ['argv'] [0], "-s <SOURCE_KEY> -t -m Message Title [-u url] [-p priority] [-d deviceid] [-i imageURL] \ n ";
echo "If messages is -, read the message from stdin. \ n";
exit ();
}

if ($ options == FALSE)
{
// Bad options.
usage ();
}
if (! isset ($ options ['s']) ||! isset ($ options ['m']) ||! isset ($ options ['t']))
{
// Missing parameters.
usage ();
}

/ **
 * Newtifry someone.
 *param String $ source The source key.
 *param String $ title The title of the notification.
 *param String $ message The message body of the notification.
 *param String | NULL $ url The URL to send along with it.
 *param Int | NULL $ priority The message priority (0-3).
 *param String | NULL $ deviceId The target deviceId.
 *param String $ backend The backend URL.
 *return Array An array with a boolean key 'success'. On false, another
 * Key is set with 'error', on true, a key is set with 'message'.
 * /
newtifry function ($ source, $ title, $ message, $ url = NULL, $ priority = 0, $ deviceid = "", $ ImageURL = "", $ backend = 'https://newtifry.appspot.com/newtifry' )
{
$ Params = array ();
$ Params ['source'] = $ source;
$ Params ['message'] = $ message;
$ Params ['title'] = $ title;
$ Params ['priority'] = $ priority;
$ Params ['deviceid'] = $ deviceid;
$ Params ['format'] = 'json';
if (false === is_null ($ url))
{
$ Params ['url'] = $ url;
}
if (false === is_null ($ imageURL))
{
$ Params ['image'] = $ imageURL;
}

$ EncodedParameters = array ();
foreach ($ params as $ key => $ value)
{
$ EncodedParameters [] = $ key. "=". urlencode ($ value);
}
$ Body = implode ("&", $ encodedParameters);
echo $ body. "\ N";
// Using CURL, send the request to the server.
$ C = curl_init ($ backend);
curl_setopt ($ c, CURLOPT_POST, true);
curl_setopt ($ c, CURLOPT_POSTFIELDS, $ body);
curl_setopt ($ c, CURLOPT_RETURNTRANSFER, true);
curl_setopt ($ c, CURLOPT_CONNECTTIMEOUT, 20);
$ Page = curl_exec ($ c);
// Parse the result.
$ Result = array ('success' => false);
if ($ page! == FALSE)
{
echo $ page. "\ N";
// The result is JSON encoded.
$ Decoded = json_decode ($ page, TRUE);
if ($ decoded === FALSE)
{
$ Result ['error'] = "Failed to decode the server response". $ Page;
}
else
{
if (isset ($ decoded ['error']))
{
$ Result ['error'] = $ decoded ['error'];
}
else
{
$ Result ['success'] = true;
$ Result ['message'] = "Success! Message size". $ Decoded ['size'];
}
}
}
else
{
$ Result ['error'] = curl_error ($ c);
}

curl_close ($ c);

return $ result;
}

// Prepare our parameters.
$ Message = $ options ['m'];

if ($ message == '-')
{
$ Message = file_get_contents ('php: // stdin');
}

$ Url = null;

if (isset ($ options ['u']))
{
$ Url = $ options ['u'];
}
$ Priority = 0;

if (isset ($ options ['p']))
{
$ Priority = $ options ['p'];
}
$ Deviceid = "";
if (isset ($ options ['d']))
{
$ Deviceid = $ options ['d'];
}

$ ImageURL = "";
if (isset ($ options ['the']))
{
$ ImageURL = $ options ['the'];
}


$ Result = newtifry ($ options ['s'], $ options ['t'], $ message, $ url, $ priority, $ deviceid, $ imageURL);

if ($ result ['success'] == FALSE)
{
echo $ result ['error'], "\ n";
exit (1);
}
else
{
echo $ result ['message'], "\ n";
exit (0);
}

?>
