### ISSUE TITLE
compilation newtifry.php

### ISSUE THREAD

**Issue by aandroide** [thunderace/newtifry#5]
Salut, ya des jours que je tente de compiler vos scripts newtifry.php mais en vain.
Je ne suis pas certain si je vois où les lettres -s, je mis ma source ou des chaînes en $ params ['source'] = $ la source;
s'il vous plaît expliquer.
Merci à l'avance
Vins

**Comment by thunderace** [comment]
From the command line : 
php newtifry.php  -s <YOUR_SOURCE_KEY> -t Title -m Message

**Comment by aandroide** [comment]
Hi, excuse me but I still do not understand .
The script is full of letters that are called , but where exactly should I enter my code ? Can ' write a piece of code please?
thank you

**Comment by thunderace** [comment]
php newtifry.php -s YOUR_SOURCE_KEY -t messagetitle -m messagebody 
where YOUR_SOURCE_KEY is from you account at https://newtifry.appspot.com/

**Comment by aandroide** [comment]
#!/usr/bin/env php Usage: -s -t Title -m Message [-u url] [-p priority] [-d
19fe81f12fcae3e249b8e4da71886190] [-i imageUrl] If messages is -, read the
message from stdin.

prejudice I tried his script but I only see these lines when I open
the script and I did not get any notification . how do I fix ?


2015-12-28 12:31 GMT+01:00 thunder <notifications@github.com>:
