### ISSUE TITLE
Do Not Disturb

### ISSUE THREAD

**Issue by snagytx** [thunderace/newtifry#6]
The "Do Not Disturb" switch is not being obeyed by the speech engine

**Comment by thunderace** [comment]
Thx i will have a  this.

**Comment by thunderace** [comment]
Question : What do you mean with 'Do Not disturb' switch. There is not such switch in Newtifry.
do you mean the android do not disturb mode on Android 6?

**Comment by snagytx** [comment]
Yes, it's at the OS level, I use Android 5, on Samsung Galaxy S 5, and use the 'Do Not Disturb' functionality and Newtify still reads the notification even the 'Do Not Disturb' is enabled. Why would you need to be disturbed at night while you sleep?

**Comment by thunderace** [comment]
I agree :).

**Comment by thunderace** [comment]
Have you try the last version?

**Comment by snagytx** [comment]
I updated using composer 2-3 days ago.

**Comment by snagytx** [comment]
Yes, I didn't anything different than the icons, anything related to "Do Not Disturb"?

**Comment by thunderace** [comment]
No, no new button, just test if android (> ) have is  'Do not disturb mode' turned on.

**Comment by snagytx** [comment]
I tested with "Do Not Disturb" enabled and the alerts are still spoken.

**Comment by thunderace** [comment]
The problem is that i have no android 5+ for testing. I will use an
emulator.

**Comment by thunderace** [comment]
I have a question : the  "Do Not Disturb" option is only available with Android 6. so i think that is option is Samsung specific, i have no API to get if this mode is on!

**Comment by snagytx** [comment]
it's there in Lollipop as well:

http://www.cnet.com/how-to/setup-interruptions-android-lollipop-do-not-disturb/

**Comment by thunderace** [comment]
Thanks you, i will look this.
