### ISSUE TITLE
Notification Tone will repeat endless

### ISSUE THREAD

**Issue by zanimax12** [thunderace/newtifry#7]
If I setup a notification tone in settings, after an incoming notification the tone will repeat endless. Is this a bug or a feature? If this is a feature, is there any possibility that the tone is only once played after an incoming notification?

**Comment by thunderace** [comment]
The notification tone is handled by the android system, not by Newtifry.
Which Newtifry version?

**Comment by zanimax12** [comment]
Newtifry Version 2.4.8 on a Samsung Galaxy Young 2 with Android 4.4.2
