### ISSUE TITLE
3 times the same notification ?

### ISSUE THREAD

**Issue by F1AZB** [thunderace/newtifry#8]
Hi 
I installation the apps from my galaxy note II to ulefone power...
The configuration are the same (don t change any thinks)  however on my ulefone power  i reveived 3 Times the same message for 1 sending from your server.. The issue is that the tts speak 3 Times the same notification ... 
Have you any idea to resolve my problème ?
In advance thanks for your help 
Regards 
Arnaud

**Comment by thunderace** [comment]
Yes, it'a bug in the Google registration. Go to https://newtifry.appspot.com/ login and look at the registered devices. I think that your ulefone is registered three time. Delete the two first registration and voilà.

**Comment by F1AZB** [comment]
Hi

Yes it ‘s exactly the issue ….

 

Thanks for your prompt answer !

Regards

Arnaud 

 

De : thunder [mailto:notifications@github.com] 
Envoyé : lundi 16 mai 2016 18:51
À : thunderace/newtifry <newtifry@noreply.github.com>
Cc : F1AZB <arnaud@xl-tech.fr>; Author <author@noreply.github.com>
Objet : Re: [thunderace/newtifry] 3 times the same notification ? (#8)

 

Yes, it'a bug in the Google registration. Go to https://newtifry.appspot.com/ login and look at the registered devices. I think that your ulefone is registered three time. Delete the two first registration and voilà.

**Comment by thunderace** [comment]
You're welcome.
