### ISSUE TITLE
Newtrify

### ISSUE THREAD

**Issue by mattyc123** [thunderace/newtifry#9]
Hi, i would like to use Newtrify for security purposes but i dont want to get notifications every time someone opens the office door. Could i set it up so that i only get a notifacation if someone doesn't disarm a message from being sent.

for example: atm, if a member of staff or anyone for that matter walked into the office i get a message immediately. 

But what im hoping to set up is that staff are able to go into the app and disarm a message being sent within 5 minutes of walking into the office.

thanks

**Comment by thunderace** [comment]
Hello. First, using Newtifry for security purpose is really not a good idea as it's based on GCM  technology and a message can take many minutes/hours to arrive to the phone.
And no, it's not possible with newtifry. You'll have to take the problem by the other side :  Allow to temporary disable the message sending.
